# _config.yml


title: "Alex Kokot"


description: "Machine learning researcher working on X, Y, Z."

# The URL for your live site (used for sitemap or RSS if you add those)
# For a user site, leave baseurl blank; for project sites, set baseurl: "/repo-name"
url: "https://amkokot.github.io"
baseurl: ""

# Markdown processor (default is kramdown; you can leave this)
markdown: kramdown


# Exclude files/folders from the build (optional)
exclude:
  - README.md
  - node_modules
  - .github

# If you ever want to use a Jekyll theme, you would add:
# theme: minima
