# _config.yml

# Site settings
title: "Alex Kokot"
description: "Machine learning researcher at University of Washington"
url: "https://amkokot.github.io"
baseurl: "/alex_kokot"

# Markdown processor
markdown: kramdown

# Exclusions (optional)
exclude:
  - README.md
  - node_modules
  - .github
